export const strings = {
  common: {
    appName: 'StackLab',
    appSubtitle: 'Gestão e Controle de Obras',
    loading: 'Carregando...',
    back: 'Voltar',
    cancel: 'Cancelar',
    save: 'Salvar',
    confirm: 'Confirmar',
    seeAll: 'Ver todas',
    today: 'Hoje',
    yesterday: 'Ontem',
    master: 'MASTER',
  },
  navigation: {
    works: 'Obras',
    overview: 'Visão Geral',
    newRDO: 'Novo RDO',
    queue: 'Fila',
    settings: 'Ajustes',
    notifications: 'Notificações',
    profile: 'Meu Perfil',
  },
  dashboard: {
    greeting: 'Olá',
    engineer: 'Engenheiro',
    lastSync: 'Última Sincronização',
    weeklySummary: 'Resumo da Semana',
    last7Days: 'Últimos 7 dias',
    activeWorks: 'Obras Ativas',
    signed: 'Assinados',
    inReview: 'Em Análise',
    pending: 'Pendentes',
    lastRdoLabel: 'ÚLTIMO RDO',
    weatherLabel: 'CLIMA',
    effectiveLabel: 'EFETIVO',
  },
  newRDO: {
    title: 'Novo RDO',
    subtitle: 'Selecione a Obra',
    description: 'Para iniciar um novo Relatório Diário de Obras, selecione em qual obra você está trabalhando hoje:',
    startAction: 'Iniciar Preenchimento',
  },
  syncQueue: {
    title: 'Fila de Sincronização',
    emptyTitle: 'Tudo em dia!',
    emptyMessage: 'Não há RDOs pendentes de sincronização.',
    syncNow: 'Sincronizar agora',
    waitingConnection: 'Aguardando conexão',
    syncedSuccess: '100% Sincronizado',
  },
  notifications: {
    title: 'Notificações',
    markAllRead: 'Marcar todas como lidas',
    emptyMessage: 'Você não possui notificações pendentes.',
  },
  settings: {
    title: 'Ajustes',
    subtitle: 'Configurações do Aplicativo',
    preferences: 'Preferências',
    syncWifiOnly: 'Sincronizar apenas via Wi-Fi',
    darkMode: 'Modo Escuro',
    about: 'Sobre',
    terms: 'Termos de Uso e Privacidade',
    helpCenter: 'Central de Ajuda',
    appVersion: 'Versão 1.2.0 (Build 42)',
  },
  profile: {
    title: 'Meu Perfil',
    editPhoto: 'Editar Foto',
    myData: 'Meus Dados',
    activeWorks: 'Obras Vinculadas',
    support: 'Suporte Técnico',
    logout: 'Sair da Conta',
  },
  login: {
    title: 'StackLab',
    subtitle: 'Gestão e Controle de Obras',
    emailPlaceholder: 'E-mail profissional',
    passwordPlaceholder: 'Senha',
    enterButton: 'Entrar no Sistema',
    quickAccess: 'Acesso Rápido para Testes',
    loginErrorTitle: 'Falha no Login',
    loginErrorMessage: 'Usuário não encontrado. Verifique seu e-mail e senha.',
  },
  accessibility: {
    notificationsButton: 'Notificações',
    profileButton: 'Perfil',
    backButton: 'Voltar',
    syncNowButton: 'Sincronizar fila agora',
    menuButton: 'Menu',
    newRdoAction: 'Criar novo Relatório Diário de Obras',
  },
  security: {
    title: 'Segurança e Permissões',
  },
} as const;

export default strings;
